//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odulsistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class odulSistemiEntities : DbContext
    {
        public odulSistemiEntities()
            : base("name=odulSistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<odul_kontrol> odul_kontrol { get; set; }
        public virtual DbSet<odul_oneri> odul_oneri { get; set; }
        public virtual DbSet<odul_tipi> odul_tipi { get; set; }
        public virtual DbSet<odul_user> odul_user { get; set; }
    }
}
